### ISSUE TITLE
com.oracle:ojdbc14:jar:1.4.2_08哪有下载

### ISSUE THREAD

**Issue by nsspw** [sogou-biztech/compass#1]
Maven编译时出现如下错误：
for project sogou.compass:compass-core:jar:2.1.3: Could not find artifact
 com.oracle:ojdbc14:jar:1.4.2_08

**Comment by comnetwork** [comment]
Oracle JDBC驱动由于授权问题，无法从Maven公共仓库获得，代码已进行修改，去除了对Oracle JDBC驱动的依赖。
