### ISSUE TITLE
执行mvn clean install -Dmaven.test.skip=true出现以下错

### ISSUE THREAD

**Issue by nsspw** [sogou-biztech/compass#2]
[INFO] sogou compass ...................................... SUCCESS [  0.270 s]
[INFO] sogou compass core ................................. FAILURE [  2.759 s]
[INFO] sogou compass delayfree ............................ SKIPPED
[INFO] sogou compass aggregation .......................... SKIPPED
[INFO] sogou compass sample ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.184 s
[INFO] Finished at: 2016-01-13T10:11:32+08:00
[INFO] Final Memory: 18M/225M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.
3.2:compile (default-compile) on project compass-core: Compilation failure: Comp
ilation failure:
[ERROR] \xxx-projects\sogou-compass\core\src\main\java\com\sogou\bizdev\compas
s\core\datasource\ShardDataSource.java:[30,7] 错误: ShardDataSource不是抽象的,
并且未覆盖CommonDataSource中的抽象方法getParentLogger()
[ERROR] \xxx-projects\sogou-compass\core\src\main\java\com\sogou\bizdev\compas
s\core\datasource\MasterSlaveDataSource.java:[34,7] 错误: MasterSlaveDataSource
不是抽象的, 并且未覆盖CommonDataSource中的抽象方法getParentLogger()
[ERROR] \xxx-projects\sogou-compass\core\src\main\java\com\sogou\bizdev\compas
s\core\datasource\SingleDataSource.java:[19,7] 错误: SingleDataSource不是抽象的,
 并且未覆盖CommonDataSource中的抽象方法getParentLogger()
[ERROR] \xxx-projects\sogou-compass\core\src\main\java\com\sogou\bizdev\compas
s\core\proxyconnection\ShardDataSourceProxyConnection.java:[27,7] 错误: ShardDat
aSourceProxyConnection不是抽象的, 并且未覆盖Connection中的抽象方法getNetworkTime
out()
[ERROR] \xxx-projects\sogou-compass\core\src\main\java\com\sogou\bizdev\compas
s\core\proxyconnection\ShardDataSourceProxyStatement.java:[18,7] 错误: ShardData
SourceProxyStatement不是抽象的, 并且未覆盖Statement中的抽象方法isCloseOnCompleti
on()
[ERROR] \xxx-projects\sogou-compass\core\src\main\java\com\sogou\bizdev\compas
s\core\proxyconnection\MasterSlaveDataSourceProxyConnection.java:[24,7] 错误: Ma
sterSlaveDataSourceProxyConnection不是抽象的, 并且未覆盖Connection中的抽象方法ge
tNetworkTimeout()
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :compass-core

**Comment by comnetwork** [comment]
多谢你的反馈，出现这个错误的原因是我们内部目前做OLTP业务的系统主要还是使用JDK1.6，JDK1.7的JDBC相关接口比JDK1.6增加了很多的方法，所以你使用JDK1.7就编译不过了，兼容JDK1.7的版本在内部测试中，很快就会发布。

**Comment by nsspw** [comment]
好的。我很关心这个中间件，因为相对独立proxy很轻量，而且风险易掌控。

**Comment by comnetwork** [comment]
感谢关注，兼容JDK1.6和1.7的代码已发布。
